# 基础配置文件
# Hexo 配置
## 文档: https://hexo.io/docs/configuration.html
## 源代码: https://github.com/hexojs/hexo/

# 网站信息
title: CHY Learning Blog  # 网站的标题
subtitle: ''  # 网站副标题
description: 'A blog about technology and life.'  # 网站描述
keywords: 'blog, technology, life'  # 网站关键词
author: CHY  # 作者
language: en  # 语言
timezone: ''  # 时区，留空使用默认时区

# URL 设置
## 设置你的网站 URL。例如，如果你使用 GitHub Pages，设置为 'https://username.github.io/project'
url: https:/redmoonnn.github.io/blog  # 网站的 URL
root: /blog/  # 根路径，通常用于 GitHub Pages 的子目录
permalink: :year/:month/:day/:title/  # 文章链接格式
permalink_defaults:
pretty_urls:
  trailing_index: true  # 设置为 false，移除 URL 结尾的 'index.html'
  trailing_html: true  # 设置为 false，移除 URL 结尾的 '.html'

# 文件目录设置
source_dir: source  # 原始文件目录
public_dir: public  # 生成的静态文件目录
tag_dir: tags  # 标签目录
archive_dir: archives  # 归档目录
category_dir: categories  # 分类目录
code_dir: downloads/code  # 代码下载目录
i18n_dir: :lang  # 国际化语言目录
skip_render:  # 跳过渲染的文件，通常留空

# 写作设置
new_post_name: :title.md  # 新建文章的文件名
default_layout: post  # 默认布局
titlecase: false  # 是否将标题转换为标题格式
external_link:
  enable: true  # 是否在新标签页打开外部链接
  field: site  # 应用于整个网站
  exclude: ''  # 不应用外部链接设置的页面，默认为空
filename_case: 0  # 文件名大小写设置，0为不变，1为小写，2为大写
render_drafts: false  # 是否渲染草稿，默认为 false
post_asset_folder: true  # 是否为每篇文章生成独立文件夹
relative_link: false  # 是否使用相对链接
future: true  # 是否允许发布未来的文章
syntax_highlighter: highlight.js  # 语法高亮使用 highlight.js
highlight:
  line_number: true  # 是否显示行号
  auto_detect: false  # 是否自动检测语言
  tab_replace: ''  # 替换 Tab 键为空格
  wrap: true  # 是否启用代码块换行
  hljs: false  # 是否使用 highlight.js 语法高亮
prismjs:
  preprocess: true  # 是否预处理代码
  line_number: true  # 是否显示行号
  tab_replace: ''  # 替换 Tab 键为空格

# 首页设置
index_generator:
  path: ''  # 首页路径
  per_page: 10  # 每页显示的文章数量
  order_by: -date  # 按日期降序排列文章

# 分类与标签
default_category: uncategorized  # 默认分类
category_map:  # 分类映射
tag_map:  # 标签映射

# 元数据设置
meta_generator: true  # 是否生成 meta generator 信息
date_format: YYYY-MM-DD  # 日期格式
time_format: HH:mm:ss  # 时间格式

# 日期/时间格式
## Hexo 使用 Moment.js 来解析和显示日期
## 你可以自定义日期格式，具体参考：http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'  # 更新选项，支持 'mtime', 'date', 'empty'

# 分页设置
per_page: 10  # 每页显示的文章数量，设置为 0 禁用分页
pagination_dir: page  # 分页目录

# 包含/排除的文件
include:  # 包含的文件
exclude:  # 排除的文件
ignore:  # 忽略的文件

# 扩展设置
theme: icarus  # 使用的主题

# 部署设置
## 文档: https://hexo.io/docs/one-command-deployment
deploy:
  type: git  # 使用 Git 部署
  repo: https://github.com/RedMoonnn/blog.git  # GitHub 仓库地址
  branch: gh-pages  # 部署到 gh-pages 分支
